### ISSUE TITLE
move VBDF integrator into a separately managed repo

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#208]
We are not actively using or improving this integrator -- should we remove it?

**Comment by adam-m-jcbs** [comment]
Being perhaps the most knowledgeable about VBDF, I'm here to put in my 2 cents.

Originally, VBDF had a lot of potential to address various issues we were having in porting reactions to the GPUs.  As our GPU strategy became more all-encompassing (just put the whole dang thing on the GPU, not just rxns or this and that), the need for VBDF became less.

I do believe there is potential in it if we find having alternative integrators that we have source-level control over and are somewhat novel in how they vectorize (at least, VBDF was novel at the time I think) is something we want to have in the code.

But we shouldn't be maintaining or shipping this code if we're not using it.

I think we can get by pretty well using our current GPU strategies.

If we do decide to remove it, I would like to help with that effort.  One, because I put a lot of the code in, and Two, because I'd like to preserve parts of it in my own repos.

**Comment by maxpkatz** [comment]
I agree with the comment that un-maintained and un-used code should not continue to be preserved in this repo. So, I support this.

I do still have interest in integrators other than VODE. Two areas to pursue for GPU performance are integrators that can use multiple threads per zone for effective parallelism, and integrators that take a fixed number of timesteps (to avoid the case where detonations in only a few zones dominate the runtime).

**Comment by adam-m-jcbs** [comment]
I have renamed the issue to reflect the strategy that Max and I agreed was best.  I believe Mike is on board as well, but feel free to comment if not.  As I'm able, I will be looking into what is needed to extract VBDF out of the repo and into one either I manage or perhaps we can make it an independent starkiller-astro project that I'll take lead on.

Comments/feedback welcome (here or in Slack).

**Comment by adam-m-jcbs** [comment]
Maybe @dwillcox should be looped in?

**Comment by maxpkatz** [comment]
I'm OK with extracting VBDF into a starkiller-astro repo or, if you prefer, into your own repo, as it is primarily your code.

**Comment by adam-m-jcbs** [comment]
My preference is `startkiller-astro/VBDF`.  But as many people contribute to `startkiller-astro`, I wanted to make sure core contributors are on board.

**Comment by adam-m-jcbs** [comment]
Update: I've been added as an org admin.  When next I'm able, this means I can go ahead and make the `starkiller-astro/VBDF` repo and plan the process of moving it out of Microphysics.  I will keep people informed on this issue and eventually via a PR to remove VBDF.

Let me know of any objections/feedback on this plan.

**Comment by dwillcox** [comment]
Thanks for pinging me @adam-m-jcbs - moving VBDF into its own repository (e.g. within starkiller-astro) makes sense for the maintainability reasons folks mentioned.

May I suggest including a driver test program and enough notes that we can run it again if we want? If you plan other development work on it, I'd be curious to learn more about what you have in mind.

I have lots of other thoughts (and hacking) for GPU reaction network integration beyond cuVODE and we can talk about this elsewhere if you like.

**Comment by adam-m-jcbs** [comment]
Don, that's great to hear that you have ideas! I did plan to make a driver/test, but am now motivated to make sure it's good since you might check it out.

My schedule is hectic, but this is a project that's straight-forward for me, so I think I'll slowly make progress in the coming weeks.
